workflows:
  android-workflow:
    name: Android Workflow
    working_directory: mobile
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/mobile/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter pub get
      - name: Build APK with Flutter
        script: | 
          touch .env.staging
          touch .env.dev
          toucn .env.example
          touch .env.prod
          touch .env
          ls
          flutter build apk --release -t lib/root/main_staging.dart -- flavor staging \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - th.thoong@gmail.com
        notify:
          success: true
          failure: false
