name: pay_cutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Network
  retrofit: 4.0.1
  json_annotation: 4.8.0
  json_serializable: 6.6.1
  dio: 5.1.1

  # Hive
  hive_flutter: 1.1.0
  hive: 2.2.3
  build_runner: 2.3.3

  # Bloc
  flutter_bloc: 8.1.2
  # bloc: 8.1.1
  equatable: 2.0.5

  # Architecture
  get_it: 7.2.0
  injectable: 2.1.0

  # Firebase
  firebase_auth: 4.4.0
  firebase_core: 2.9.0
  google_sign_in: 6.0.2
  firebase_messaging: 14.4.0

  # UI
  lottie: 2.3.1
  fl_chart: 0.61.0
  flutter_speed_dial: 6.2.0

  # Utils
  flutter_dotenv: 5.0.2
  timeago: ^3.3.0
  tiengviet: 0.5.0

  # Scan & QR code
  google_mlkit_text_recognition: 0.5.0
  camera: 0.10.3+2
  path_provider: 2.0.14
  image_picker: 0.8.7+1
  qr_flutter: 4.0.0
  mobile_scanner: 3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  flutter_gen_runner: 5.2.0
  injectable_generator: 2.1.4
  hive_generator: 2.0.0
flutter:

  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
    - .env.staging
    - .env.example
    - assets/anim/
    - assets/icons/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_gen:
  output: lib/generated/

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
    